# config.yaml

database:
  dbUser: "{{ssm:/prod/db/user}}"
  dbPassword: "{{ssm:/prod/db/password}}"
  dbHost: "{{secretsmanager:/prod/db/host}}" // again, config file itself should not have any sensitive data. All sensitive data should be stored in K8s secret manager
  dbPort: "{{secretsmanager:/prod/db/port}}"

api:
  paymentGatewayKey: "Fg7H2yLdM8VpQz3N6RbXtPWaK4CsJ9T5"  
  smsProviderKey: "X1Y2Z3A4B5C6D7E8F9G0H1I2J3K4L5M6" 
  internalServiceToken: "{{secretsmanager:/prod/api/internalService}}"  
  analyticsIntegrationKey: "{{ssm:/prod/api/analytics}}"  

thirdParty:
  awsAccessKey: "{{secretsmanager:/aws/access-key}}"
  awsSecretKey: "{{ssm:/aws/secret-key}}"
  analyticsKey: "{{secretsmanager:/analytics/key}}"
  smsServiceKey: "{{ssm:/sms/service-key}}"

